# RANS湍流建模 - 長期穩定性測試配置
# 基於 rans_optimized.yml，專門用於驗證500-1000 epochs穩定性

# 物理模型設定
physics:
  type: "RANS"
  model: "k_epsilon"
  
  # 流體性質
  fluid:
    density: 1.0
    viscosity: 1.6e-3    # 分子黏度 (水的大約值)
    turbulent_prandtl:
      momentum: 1.0      # 動量湍流Prandtl數
      k: 1.0            # k方程湍流Prandtl數
      epsilon: 1.3      # ε方程湍流Prandtl數
  
  # k-ε模型常數
  turbulence_constants:
    C_mu: 0.09      # 湍流黏度常數
    C_1e: 1.44      # ε方程常數1
    C_2e: 1.92      # ε方程常數2
    sigma_k: 1.0    # k方程Prandtl數
    sigma_e: 1.3    # ε方程Prandtl數
  
  # 計算域
  domain:
    x_range: [0.0, 4.0]
    y_range: [0.0, 2.0]
    t_range: [0.0, 1.0]
    
  # 邊界條件 - 湍流量
  boundary_conditions:
    type: "dirichlet"
    wall_velocity: [0.0, 0.0]
    inlet_profile: "parabolic"
    # 湍流量邊界條件
    wall_k: 0.0     # 壁面湍動能
    wall_epsilon: 0.1  # 壁面耗散率
    inlet_k: 0.01   # 入口湍動能
    inlet_epsilon: 0.1  # 入口耗散率

# 損失函數權重 - 穩定性測試版本
losses:
  # 基本損失權重
  data_weight: 1.0
  boundary_weight: 1.0
  initial_weight: 1.0
  
  # RANS方程權重 - 已驗證的平衡權重
  momentum_x_weight: 1.0      # x方向動量方程
  momentum_y_weight: 1.0      # y方向動量方程
  continuity_weight: 1.0      # 連續方程
  k_equation_weight: 1.0e-4   # 湍動能方程 (平衡量級)
  epsilon_equation_weight: 1.0e-5 # 耗散率方程 (平衡量級)
  
  # 先驗與正則化
  prior_weight: 0.3
  source_l1: 1.0e-6
  
  # 湍流特有正則化
  k_min_constraint: 1.0e-6    # k ≥ 0 約束
  epsilon_min_constraint: 1.0e-6  # ε ≥ 0 約束
  realizability_weight: 0.1   # 可實現性約束
  
  # 動態權重
  adaptive_weighting: true
  weight_update_freq: 1000
  grad_norm_alpha: 0.9
  
  # 時間因果權重
  causal_weighting: true
  causal_eps: 1.0

# 訓練設定 - 長期穩定性測試
training:
  optimizer: "adam"
  lr: 5.0e-4         # 已驗證的學習率
  weight_decay: 1.0e-5
  lr_scheduler: "cosine"
  
  max_epochs: 500      # 長期穩定性測試
  batch_size: 2048     # 已驗證的批次大小
  validation_freq: 10   # 增加驗證頻率以監控穩定性
  checkpoint_freq: 50   # 更頻繁的檢查點保存
  early_stopping: false
  patience: 20000
  
  # 取樣策略
  sampling:
    pde_points: 15000    # 已驗證的PDE點數
    boundary_points: 2000
    initial_points: 1000
    
  # 課程學習 - 已驗證的策略
  curriculum: true
  curriculum_schedule: "exponential"
  curriculum_stages:
    - epochs: 30        # 階段1：只訓練平均流動
      active_losses: ["momentum", "continuity", "data", "boundary"]
    - epochs: 60        # 階段2：加入湍動能
      active_losses: ["momentum", "continuity", "k_equation", "data", "boundary"]
    - epochs: -1        # 階段3：全部方程
      active_losses: ["all"]

# Ensemble 與不確定性量化
ensemble:
  enabled: false       # 穩定性測試暫時關閉ensemble
  n_models: 8
  init_schemes: ["xavier", "he", "orthogonal"]
  dropout_rate: 0.1

# 模型架構
model:
  type: "fourier_mlp"
  
  # 網路結構 - 湍流量輸出
  in_dim: 3     # [t, x, y]
  out_dim: 6    # [u, v, p, k, ε, S] (速度、壓力、湍動能、耗散率、源項)
  width: 512    # 已驗證的網路寬度
  depth: 6      # 已驗證的深度
  activation: "tanh"
  
  # Fourier Features
  fourier_m: 64  # 已驗證的Fourier模態
  fourier_sigma: 8.0
  
  # VS-PINN 變數尺度化
  scaling:
    enable: true
    learnable: true
    input_norm: "standard"
    output_norm: "standard"
    method: "adaptive"
    update_freq: 1000
    momentum: 0.9

# 數據設定
data:
  type: "synthetic"
  noise_level: 0.01
  sparse_sensing: true
  n_sensors: 8
  sensor_placement: "qr_pivot"

# 實驗設定
experiment:
  name: "rans_stability_test"
  device: "auto"
  precision: "float32"
  seed: 42
  
# 重現性設定
reproducibility:
  deterministic: true
  benchmark: false
  num_workers: 4

# 日誌與輸出
logging:
  level: "INFO"
  tensorboard: false
  wandb: false
  output_dir: "outputs/rans_stability"
  save_predictions: false
  save_freq: 100

# 檢查點與恢復
checkpoint:
  enabled: true
  save_best: true
  save_last: true
  monitor: "total_loss"
  mode: "min"