# Channel Flow Re1000 PINNs 穩定版配置檔案
# 針對權重爆炸問題的修復版本

# 基本實驗設定
experiment:
  name: "pinnx_channel_flow_re1000_stable"
  version: "v1.1"
  seed: 42
  device: "auto"
  precision: "float32"
  description: "Channel Flow Re1000 穩定權重版本"

# 資料相關設定 - JHTDB Channel Flow Re1000 特化
data:
  source: "jhtdb"
  dataset: "channel"
  
  jhtdb_config:
    enabled: true
    dataset_name: "channel"
    description: "通道流 (Re_tau=1000)"
    domain:
      x: [0, 25.13]
      y: [-1.0, 1.0]
      z: [0, 9.42]
    resolution:
      x: 2048
      y: 512
      z: 1536
    time_range: [0.0, 26.0]
    dt: 0.0065
    variables: ['u', 'v', 'w', 'p']
  
  normalize: true
  cache_dir: "./data/jhtdb/channel_flow_re1000"
  noise_sigma: 0.02
  dropout_prob: 0.10
  
  slice_config:
    plane: "xy"
    z_position: 4.71
    steady_state: true
    time_average_window: [20.0, 26.0]

# 感測點配置
sensors:
  K: 16  # 感測點數量 - 使用16個點（Fix 6 驗證）
  selection_method: "qr_pivot"
  sensor_file: "sensors_K16_qr_pivot.npz"  # 明確指定快取檔案
  spatial_coverage: "wall_biased"
  wall_enhancement: true
  wall_region_ratio: 0.4
  log_layer_coverage: true
  
  physics_guided:
    boundary_layer_focus: true
    shear_stress_regions: true
    turbulence_intensity_regions: true

# 模型架構設定
model:
  type: "fourier_mlp"
  in_dim: 2  # (x, y) 2D 通道流
  out_dim: 3  # (u, v, p) - 修正：2D 流場只有3個輸出
  width: 256
  depth: 6
  activation: "tanh"
  
  fourier_m: 48
  fourier_sigma: 3.0
  
  scaling:
    learnable: true
    input_norm: "channel_flow"
    output_norm: "friction_velocity"
    friction_velocity: 1.0
    channel_half_height: 1.0
    viscous_length: 1.0e-3

# 物理設定
physics:
  nu: 1.0e-3
  rho: 1.0
  
  channel_flow:
    Re_tau: 1000.0
    Re_bulk: 41980.0
    u_tau: 1.0
    pressure_gradient: -1.0
    
  domain:
    x_range: [0.0, 25.13]
    y_range: [-1.0, 1.0]
    
  boundary_conditions:
    wall_velocity: [0.0, 0.0]
    wall_location: [-1.0, 1.0]
    periodic_x: true
    pressure_driven: true
    mean_pressure_gradient: -1.0

# 損失函數權重 - 🔧 穩定化設定
losses:
  # 基本損失權重 - 保守設定
  data_weight: 10.0
  boundary_weight: 10.0
  
  # PDE 殘差權重
  momentum_x_weight: 1.0
  momentum_y_weight: 1.0
  continuity_weight: 1.0
  
  # Channel Flow 特有約束
  wall_constraint_weight: 5.0
  periodicity_weight: 2.0
  pressure_gradient_weight: 1.0
  
  # 物理先驗與正則化
  prior_weight: 0.3
  source_l1: 1.0e-6
  gradient_penalty: 1.0e-4
  
  # 🔧 關鍵修復：禁用動態權重避免爆炸
  adaptive_weighting: false  # 暫時禁用
  weight_update_freq: 1000
  grad_norm_alpha: 0.12      # 降低到論文建議值
  
  # 時間因果權重
  causal_weighting: false

# 訓練設定
training:
  optimizer: "adam"
  lr: 8.0e-4
  weight_decay: 1.0e-5
  lr_scheduler: "cosine"
  
  max_epochs: 15000
  batch_size: 1024
  validation_freq: 500
  checkpoint_freq: 2000
  early_stopping: true
  patience: 3000
  
  sampling:
    pde_points: 4096  # PDE 殘差計算點數 - 標準化為4096個點
    boundary_points: 1000
    wall_clustering: 0.3
    
  curriculum: true
  curriculum_schedule: "exponential"
  curriculum_stages:
    - epochs: 50
      active_losses: ["boundary", "wall_constraint"]
      sampling_focus: "wall"
    - epochs: 150
      active_losses: ["boundary", "wall_constraint", "momentum"]
      sampling_focus: "boundary_layer"
    - epochs: -1
      active_losses: ["all"]
      sampling_focus: "full_domain"

# Ensemble 與不確定性量化
ensemble:
  enable: false
  n_models: 8
  seeds: [0, 1, 2, 3, 4, 5, 6, 7]
  uncertainty_quantification: true
  confidence_level: 0.95

# 評估設定
evaluation:
  grid_resolution: [256, 128]
  
  metrics:
    - "relative_l2"
    - "wall_shear_stress"
    - "velocity_profile"
    - "friction_coefficient"
    - "turbulence_statistics"
    - "pressure_drop"
    - "uncertainty_corr"
    
  thresholds:
    l2_error: 0.10
    wall_shear_error: 0.05
    velocity_profile_error: 0.08
    rmse_improvement: 0.30
    uq_correlation: 0.6
    
  channel_flow_validation:
    log_law_region: [30, 300]
    von_karman_constant: 0.41
    wake_parameter: 0.55

# 日誌與儲存
logging:
  level: "info"
  log_freq: 100
  save_predictions: true
  save_checkpoints: true
  
  save_velocity_profiles: true
  save_wall_quantities: true
  save_turbulence_fields: true
  
  wandb:
    project: "pinnx-channel-flow-re1000-stable"
    entity: null
    tags: ["pinns", "inverse", "channel_flow", "re1000", "jhtdb", "stable"]

# 重現性設定
reproducibility:
  deterministic: true
  benchmark: false
  num_workers: 4

# Channel Flow Re1000 專用驗證設定
validation:
  dns_benchmark: true
  dns_data_path: "./data/jhtdb/channel_flow_re1000/dns_reference"
  
  turbulence_statistics:
    reynolds_stress: true
    turbulent_kinetic_energy: true
    dissipation_rate: true
    
  wall_quantities:
    skin_friction: true
    heat_transfer: false
    pressure_fluctuation: true

# 效能優化設定
performance:
  mixed_precision: true
  gradient_checkpointing: false
  vectorized_operations: true
  parallel_sampling: true
  max_gpu_memory_fraction: 0.9
  clear_cache_freq: 1000