# ============================================================================
# PINNs 逆重建 - 2D 切片配置
# ============================================================================
# 目標：從 2D x-y 切片（流向-壁法向）進行稀疏重建驗證
# 用途：快速驗證方法可行性，建立基準性能
# 資料：JHTDB Channel Flow Re_tau=1000 時間平均 2D 切片
# ============================================================================

# 繼承主配置
_base_: "inverse_reconstruction_main.yml"

# ============================================================================
# 實驗設定覆寫
# ============================================================================
experiment:
  name: "inverse_2d_slice"
  description: "2D steady-state slice reconstruction from sparse sensors"
  phase: "validation"

# ============================================================================
# 資料配置 - 2D 切片特化
# ============================================================================
data:
  # 2D 切片配置
  slice_config:
    plane: "xy"              # x-y 平面（流向-壁法向）
    z_position: 4.71         # z = 3π/2 中間切片
    steady_state: true       # 時間平均場
    time_average_window: [20.0, 26.0]  # 統計穩態窗口
  
  # 資料維度
  dimensionality: "2d"
  
  # 快取配置
  cache_dir: "./data/jhtdb/channel_flow_re1000/2d_slice"
  use_cache: true

# ============================================================================
# 感測點配置 - 2D 優化
# ============================================================================
sensors:
  K: 50  # 2D 切片感測點數
  
  # QR-pivot 配置
  qr_pivot:
    basis_source: "lowfi"
    snapshot_ensemble_size: 50  # 2D 需要較少快照
  
  # 2D 物理引導策略
  physics_guided:
    wall_enhancement: true
    wall_region_ratio: 0.4
    boundary_layer_focus: true
    log_layer_coverage: true
    wake_region_coverage: true

# ============================================================================
# 模型架構 - 2D 輸入
# ============================================================================
model:
  in_dim: 2      # [x, y] 2D 定常
  out_dim: 3     # [u, v, p] 速度 + 壓力（無 w 分量）
  width: 200
  depth: 8
  activation: "sine"
  
  # Fourier Features
  fourier:
    enabled: true
    m: 64
    sigma: 5.0
  
  # VS-PINN 尺度化
  scaling:
    enabled: true
    learnable: true
    input_scales:
      x: 25.13
      y: 1.0
    output_scales:
      u: 1.0
      v: 0.1
      p: 1.0

# ============================================================================
# 物理配置 - 2D NSE
# ============================================================================
physics:
  domain:
    x_range: [0.0, 25.13]
    y_range: [-1.0, 1.0]
    dimensionality: "2d"
  
  # 2D Navier-Stokes
  equations: "nse_2d_steady"
  
  boundary_conditions:
    wall:
      type: "no_slip"
      locations: [-1.0, 1.0]
      velocity: [0.0, 0.0]
    periodic:
      x: true

# ============================================================================
# 損失函數 - 2D 特化
# ============================================================================
losses:
  # 資料與邊界
  data_weight: 1.0
  boundary_weight: 1.0
  wall_constraint_weight: 1.0
  
  # 2D 動量方程
  momentum_x_weight: 1.0
  momentum_y_weight: 1.0
  continuity_weight: 1.0
  
  # 先驗與正則
  prior_weight: 0.3
  source_l1: 1.0e-6
  source_l2: 1.0e-8
  gradient_penalty: 1.0e-4
  
  # 動態權重
  adaptive_weighting:
    enabled: true
    method: "gradnorm"
    update_freq: 1000
    alpha: 0.9
  
  # 不使用因果權重
  causal_weighting:
    enabled: false

# ============================================================================
# 訓練配置 - 2D 優化
# ============================================================================
training:
  # Adam 階段
  optimizer_stage1:
    type: "adam"
    lr: 1.0e-3
    weight_decay: 1.0e-6
  
  # L-BFGS 階段
  optimizer_stage2:
    type: "lbfgs"
    lr: 0.5
    max_iter: 20
  
  optimizer_schedule:
    stage1_epochs: 10000
    stage2_epochs: 5000
  
  # 訓練參數
  max_epochs: 15000
  batch_size: 1024
  validation_freq: 500
  checkpoint_freq: 2000
  
  # 早停
  early_stopping:
    enabled: true
    patience: 3000
    min_delta: 1.0e-6
  
  # 2D 採樣策略
  sampling:
    pde_points: 4096
    boundary_points: 1000
    wall_clustering: 0.3
    prior_points: 2000
  
  # 課程學習
  curriculum:
    enabled: true
    strategy: "progressive_physics"
    stages:
      # 階段 1: 邊界擬合 (0-2000)
      - name: "boundary_fitting"
        epochs: 2000
        active_losses:
          data_weight: 1.0
          boundary_weight: 10.0
          wall_constraint_weight: 10.0
          momentum_x_weight: 0.1
          momentum_y_weight: 0.1
          continuity_weight: 0.1
        sampling_focus: "wall"
      
      # 階段 2: 動量方程 (2000-7000)
      - name: "momentum_incorporation"
        epochs: 5000
        active_losses:
          data_weight: 1.0
          boundary_weight: 5.0
          wall_constraint_weight: 5.0
          momentum_x_weight: 1.0
          momentum_y_weight: 1.0
          continuity_weight: 1.0
          prior_weight: 0.3
        sampling_focus: "boundary_layer"
      
      # 階段 3: 完整物理 (7000-15000)
      - name: "full_physics"
        epochs: 8000
        active_losses:
          data_weight: 1.0
          boundary_weight: 1.0
          wall_constraint_weight: 1.0
          momentum_x_weight: 1.0
          momentum_y_weight: 1.0
          continuity_weight: 1.0
          prior_weight: 0.3
          source_l1: 1.0e-6
        sampling_focus: "full_domain"

# ============================================================================
# 評估配置 - 2D 網格
# ============================================================================
evaluation:
  grid_resolution: [512, 256]  # [x, y] 2D 網格
  
  metrics:
    - "relative_l2"
    - "wall_shear_stress"
    - "velocity_profile"
    - "friction_coefficient"
    - "log_law_validation"
    - "pressure_drop"
  
  thresholds:
    l2_error_u: 0.15
    l2_error_v: 0.15
    l2_error_p: 0.15
    rmse_improvement_statistics: 0.30
    rmse_improvement_wall_shear: 0.30

# ============================================================================
# 日誌與輸出
# ============================================================================
logging:
  output_dir: "./results/2d_slice"
  checkpoint_dir: "./checkpoints/2d_slice"
  log_dir: "./logs/2d_slice"
  
  wandb:
    enabled: false
    project: "pinnx-inverse-2d"
    tags:
      - "2d_slice"
      - "steady_state"
      - "validation"

# ============================================================================
# 低保真先驗 - 2D RANS
# ============================================================================
prior:
  type: "rans_ke"
  mesh_resolution: [128, 64]
  data_path: "./data/lowfi/channel_re1000_2d_rans_ke.npz"
  
  consistency_strategy: "region_weighted"
  consistency_regions:
    bulk_flow:
      weight: 0.5
      y_plus_range: [300, 1000]
    buffer_layer:
      weight: 0.3
      y_plus_range: [30, 300]
    viscous_sublayer:
      weight: 0.1
      y_plus_range: [0, 30]
