# ========================================
# PirateNet 快速整合測試配置
# ========================================
# 用途: 本地測試 SOAP + Swish + Steps Scheduler 整合
# 規模: 縮小網路與資料量，100 epochs

experiment:
  name: "piratenet_quick_test"
  version: "v1.0"
  seed: 42
  device: "auto"
  precision: "float32"
  description: "PirateNet 快速整合測試 (100 epochs)"

# 資料配置（縮小規模）
data:
  type: "jhtdb_channel"
  dataset: "channel"
  re_tau: 1000
  
  data_dir: "./data/jhtdb"
  lowfi_dir: "./data/lowfi"
  
  # 啟用 JHTDB 資料載入
  jhtdb_config:
    enabled: true
    dataset: "channel"
    re_tau: 1000
    time_step: 0.0
    use_cache: true
    
    # Domain configuration (for channel_flow_loader)
    domain:
      x: [0.0, 25.132741228718345]
      y: [0.0, 2.0]
      z: [0.0, 9.42477796076938]
    
    # Physical parameters
    Re_tau: 1000.0
    nu: 5.0e-5
    u_tau: 0.04997
  
  # Also keep at top level for physics module
  domain:
    x_min: 0.0
    x_max: 25.132741228718345
    y_min: 0.0
    y_max: 2.0
    z_min: 0.0
    z_max: 9.42477796076938
  
  # 縮小感測點與配點
  num_sensors: 30
  sensor_type: "qr_pivot"
  sensor_noise: 0.01
  
  num_collocation: 2048  # 減少至 2048（原: 8192）
  num_boundary: 256
  num_initial: 128

# 感測點配置
sensors:
  K: 30  # 感測點數量（快速測試）
  selection_method: "qr_pivot"
  spatial_coverage: "optimal"

# 模型配置（縮小規模）
model:
  type: "enhanced_fourier_mlp"
  
  in_dim: 3   # 3D: (x, y, z) - VS-PINN 需要 3D 輸入
  out_dim: 4  # 3D: (u, v, w, p)
  depth: 4           # 減少至 4 層（原: 6）
  width: 256         # 減少至 256（原: 768）
  
  activation: "swish"
  
  # Fourier Features
  use_fourier: true
  fourier_m: 32      # 減少至 32（原: 64）
  fourier_sigma: 2.0
  fourier_multiscale: false
  trainable_fourier: false
  
  # RWF
  use_rwf: true
  rwf_scale_mean: 1.0
  rwf_scale_std: 0.1
  
  use_residual: false
  use_layer_norm: false
  dropout: 0.0

# 訓練配置（100 epochs 測試）
training:
  epochs: 100          # 快速測試: 100 epochs
  batch_size: 2048
  
  # SOAP 優化器（PirateNet 核心組件）
  optimizer:
    type: "soap"
    lr: 5.0e-4             # SOAP 建議較低初始學習率
    betas: [0.95, 0.99]    # SOAP 建議的動量參數
    shampoo_beta: 0.95     # Shampoo 預處理參數
    precondition_frequency: 2  # 預處理頻率
    weight_decay: 0.0
  
  # Steps-based Scheduler
  scheduler:
    type: "warmup_exponential_steps"
    warmup_steps: 200       # 減少至 200（原: 2000）
    total_steps: 10000      # 假設 100 epochs × 100 steps/epoch
    decay_steps: 500        # 減少至 500（原: 2000）
    decay_gamma: 0.9
    min_lr: 1.0e-6
  
  # 採樣配置
  sampling:
    pde_points: 2048
    boundary_points: 256
    wall_clustering: 0.3
  
  validation_freq: 20
  checkpoint_freq: 50
  log_interval: 10

# 損失權重
losses:
  data_loss_weight: 100.0
  pde_loss_weight: 1.0
  wall_loss_weight: 10.0
  initial_loss_weight: 50.0
  prior_weight: 0.1  # 低保真先驗權重（軟約束）
  
  adaptive_weights:
    enabled: true
    method: "gradnorm"
    alpha: 1.5
    update_frequency: 500  # 減少至 500（原: 1000）
  
  causal_weights:
    enabled: true
    epsilon: 1.0
    tol: 0.1

# 物理配置
physics:
  type: "vs_pinn_channel_flow"
  nu: 5.0e-5
  re_tau: 1000
  u_tau: 0.04997
  
  # 計算域（3D 格式 - VS-PINN 標準）
  domain:
    x_min: 0.0
    x_max: 25.132741228718345  # 8π
    y_min: 0.0
    y_max: 2.0                 # 2h (通道高度)
    z_min: 0.0
    z_max: 9.42477796076938    # 3π
  
  # VS-PINN 縮放因子
  scaling:
    use_scaling: true
    N_x: 0.33
    N_y: 1.00
    N_z: 0.25


# 輸出配置
output:
  checkpoint_dir: "./checkpoints/piratenet_quick_test"
  results_dir: "./results/piratenet_quick_test"
  visualization_dir: "./results/piratenet_quick_test/visualizations"
  save_predictions: true
  save_frequency: 50

# 日誌配置
logging:
  level: "info"
  log_freq: 10
  tensorboard: false  # 關閉 TensorBoard（快速測試）
  wandb: false
  
  metrics:
    - "total_loss"
    - "data_loss"
    - "pde_loss"
    - "wall_loss"
    - "learning_rate"

# 早停配置
early_stopping:
  enabled: false
  patience: 50
  min_delta: 1.0e-6
  monitor: "total_loss"

# 可重現性配置
reproducibility:
  deterministic: true
  benchmark: false
