# ====================================================================
# 標準化配置 2000 Epoch 訓練（基於 main.yml）
# ====================================================================
# 目標：驗證標準化配置的長期訓練穩定性
# 預期時間：2-4 小時（視硬體而定）
# ====================================================================

experiment:
  name: "normalization_main_2000epochs"
  version: "v1.0"
  seed: 42
  device: "auto"
  precision: "float32"
  description: "基於 main.yml 的 2000 epoch 標準化訓練測試"

# ====================================================================
# 重現性設定
# ====================================================================
reproducibility:
  deterministic: true
  benchmark: false
  num_workers: 2

# ====================================================================
# 資料來源設定
# ====================================================================
data:
  source: "jhtdb"
  dataset: "channel"
  
  jhtdb_config:
    enabled: true
    dataset_name: "channel"
    description: "通道流 (Re_tau=1000)"
    domain:
      x: [0, 25.13]
      y: [-1.0, 1.0]
      z: [0, 9.42]
    resolution:
      x: 2048
      y: 512
      z: 1536
    time_range: [0.0, 26.0]
    dt: 0.0065
    variables: ['u', 'v', 'w', 'p']
  
  normalize: true
  cache_dir: "./data/jhtdb/channel_flow_re1000"
  noise_sigma: 0.0
  dropout_prob: 0.0
  
  slice_config:
    plane: "xy"
    z_position: 4.71
    steady_state: true
    time_average_window: [20.0, 26.0]

# ====================================================================
# 標準化配置（從訓練資料自動計算）
# ====================================================================
normalization:
  type: "training_data_norm"
  variables: ["u", "v", "w", "p"]
  params: {}

# ====================================================================
# 感測點配置（使用現有 K=50 文件）
# ====================================================================
sensors:
  K: 50                                # 感測點數量（使用現有文件）
  strategy: "qr_pivot"
  sensor_file: "sensors_K50_qr_pivot.npz"  # 使用已驗證的感測點文件

# ====================================================================
# 模型架構配置
# ====================================================================
model:
  type: "fourier_mlp"
  width: 200
  depth: 8
  out_dim: 4
  activation: "sine"
  
  use_residual: false
  use_layer_norm: false
  dropout: 0.0
  use_rwf: true
  rwf_scale_std: 0.1
  sine_omega_0: 1.0
  use_gradient_checkpointing: false    # 關閉梯度檢查點（已修正配置路徑）
  
  output_ranges:
    u: "auto"
    v: "auto"
    w: "auto"
    p: "auto"
  
  fourier_features:
    enabled: true
    axes_config:
      x: [1, 2, 4, 8]
      y: []
      z: [1, 2, 4, 8]
    domain_lengths:
      x: 25.13
      y: 2.0
      z: 9.42
    trainable: false

# ====================================================================
# Fourier 退火配置
# ====================================================================
fourier_annealing:
  enabled: true
  strategy: "custom"
  axes_names: ['x', 'y', 'z']
  
  stages:
    - end_ratio: 0.3                  # 前 30% epochs (0-600)
      frequencies: [1, 2]
      description: "低頻預熱"
    - end_ratio: 0.6                  # 中間 30% (600-1200)
      frequencies: [1, 2, 4]
      description: "中頻解鎖"
    - end_ratio: 1.0                  # 最後 40% (1200-2000)
      frequencies: [1, 2, 4, 8]
      description: "全頻段"

# ====================================================================
# 物理設定
# ====================================================================
physics:
  type: "vs_pinn_channel_flow"
  nu: 5.0e-5
  rho: 1.0
  
  channel_flow:
    Re_tau: 1000.0
    Re_bulk: 39998.0
    u_tau: 0.04997
    pressure_gradient: 0.0025
  
  domain:
    x_range: [0.0, 25.13]
    y_range: [-1.0, 1.0]
    z_range: [0.0, 9.42]
  
  boundary_conditions:
    wall_velocity: [0.0, 0.0, 0.0]
    wall_location: [-1.0, 1.0]
    periodic_x: true
    periodic_z: true
    pressure_driven: true
    mean_pressure_gradient: 0.0025

# ====================================================================
# 損失函數權重
# ====================================================================
losses:
  data_weight: 10.0
  boundary_weight: 10.0
  
  momentum_x_weight: 1.0
  momentum_y_weight: 1.0
  momentum_z_weight: 1.0
  continuity_weight: 1.0
  
  wall_constraint_weight: 5.0
  periodicity_weight: 5.0
  pressure_gradient_weight: 1.0
  
  prior_weight: 0.3
  source_l1: 1.0e-6
  gradient_penalty: 1.0e-4
  
  adaptive_weighting: true
  weight_update_freq: 100
  grad_norm_alpha: 0.15
  
  causal_weighting: false

# ====================================================================
# 訓練設定（2000 Epoch）
# ====================================================================
training:
  optimizer: "adam"                   # 使用 Adam（MPS 兼容）
  lr: 1.0e-3
  weight_decay: 1.0e-5
  
  lr_scheduler:
    type: "cosine_warm_restarts"
    T_0: 200                          # 每 200 epochs 重啟一次
    T_mult: 2
    eta_min: 1.0e-6
  
  epochs: 2000                        # ⭐ 2000 Epoch 訓練
  max_epochs: 2000
  batch_size: 10000
  validation_freq: 100                # 每 100 epochs 驗證
  checkpoint_freq: 200                # 每 200 epochs 保存檢查點
  log_interval: 50                    # 每 50 epochs 輸出日誌
  
  early_stopping:
    enabled: true                     # 啟用早停（防止過擬合）
    patience: 500
    min_delta: 1.0e-6
  
  sampling:
    pde_points: 20000
    boundary_points: 5000
    wall_clustering: 0.3
  
  curriculum: true
  gradient_clip: 1.0

# ====================================================================
# Ensemble 設定（暫不啟用）
# ====================================================================
ensemble:
  enable: false
  n_models: 5
  diversity_weight: 0.1
  uncertainty_threshold: 0.15

# ====================================================================
# 評估設定
# ====================================================================
evaluation:
  grid_resolution: [128, 32, 128]
  
  metrics:
    - "relative_l2"
    - "wall_shear_stress"
    - "velocity_profile"
    - "turbulence_statistics"
    - "pressure_drop"
    - "mass_conservation"
    - "energy_spectrum"
  
  thresholds:
    l2_error: 0.15
    wall_shear_error: 0.08
    velocity_profile_error: 0.10
    rmse_improvement: 0.30
    spectrum_rmse: 0.25

# ====================================================================
# 檢查點與日誌
# ====================================================================
checkpointing:
  save_dir: "./checkpoints/normalization_main_2000epochs"
  save_best: true
  save_latest: true
  save_interval: 200

logging:
  log_dir: "./log/normalization_main_2000epochs"
  tensorboard: true
  wandb: false
  level: "INFO"                       # 使用 'level' 以兼容 train.py (L1176)
  log_level: "INFO"                   # 保留備用

# ====================================================================
# 訓練計畫
# ====================================================================
# 階段 1 (0-600 epochs):     低頻預熱，Fourier [1,2]
# 階段 2 (600-1200 epochs):  中頻解鎖，Fourier [1,2,4]
# 階段 3 (1200-2000 epochs): 全頻段，Fourier [1,2,4,8]
# 
# 預期檢查點：epoch_200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000
# 預期驗證：每 100 epochs（20 次驗證）
# ====================================================================
