experiment:
  name: normalization_quick_test_10epochs
  version: v1.0
  seed: 42
  device: auto
  precision: float32
  description: 標準化配置驗證測試（10 epochs）
reproducibility:
  deterministic: true
  benchmark: false
  num_workers: 2
data:
  source: jhtdb
  dataset: channel
  jhtdb_config:
    enabled: true
    dataset_name: channel
    description: 通道流 (Re_tau=1000)
    domain:
      x:
      - 0
      - 25.13
      y:
      - -1.0
      - 1.0
      z:
      - 0
      - 9.42
    resolution:
      x: 2048
      y: 512
      z: 1536
    time_range:
    - 0.0
    - 26.0
    dt: 0.0065
    variables:
    - u
    - v
    - w
    - p
  normalize: true
  cache_dir: ./data/jhtdb/channel_flow_re1000
  noise_sigma: 0.0
  dropout_prob: 0.0
  slice_config:
    plane: xy
    z_position: 4.71
    steady_state: true
    time_average_window:
    - 20.0
    - 26.0
normalization:
  type: training_data_norm
  variables:
  - u
  - v
  - w
  - p
  params: {}
sensors:
  K: 50
  strategy: qr_pivot
  sensor_file: ./data/jhtdb/channel_flow_re1000/sensors_K50_qr_pivot.npz
  hybrid_config:
    wall_ratio: 0.4
    qr_ratio: 0.6
    wall_thickness: 0.1
model:
  type: fourier_mlp
  width: 200
  depth: 8
  out_dim: 4
  activation: sine
  use_residual: false
  use_layer_norm: false
  dropout: 0.0
  use_rwf: true
  rwf_scale_std: 0.1
  sine_omega_0: 1.0
  output_ranges:
    u: auto
    v: auto
    w: auto
    p: auto
  fourier_features:
    enabled: true
    axes_config:
      x:
      - 1
      - 2
      - 4
      - 8
      y: []
      z:
      - 1
      - 2
      - 4
      - 8
    domain_lengths:
      x: 25.13
      y: 2.0
      z: 9.42
    trainable: false
  scaling:
    learnable: true
    input_norm: channel_flow
    output_norm: friction_velocity
    friction_velocity: 1.0
    channel_half_height: 1.0
    viscous_length: 0.001
  use_gradient_checkpointing: false
fourier_annealing:
  enabled: false
  strategy: custom
  axes_names:
  - x
  - y
  - z
  stages:
  - end_ratio: 0.3
    frequencies:
    - 1
    - 2
    description: 低頻預熱
  - end_ratio: 0.6
    frequencies:
    - 1
    - 2
    - 4
    description: 中頻解鎖
  - end_ratio: 1.0
    frequencies:
    - 1
    - 2
    - 4
    - 8
    description: 全頻段
physics:
  type: vs_pinn_channel_flow
  nu: 5.0e-05
  rho: 1.0
  channel_flow:
    Re_tau: 1000.0
    Re_bulk: 39998.0
    u_tau: 0.04997
    pressure_gradient: 0.0025
  domain:
    x_range:
    - 0.0
    - 25.13
    y_range:
    - -1.0
    - 1.0
    z_range:
    - 0.0
    - 9.42
  boundary_conditions:
    wall_velocity:
    - 0.0
    - 0.0
    - 0.0
    wall_location:
    - -1.0
    - 1.0
    periodic_x: true
    periodic_z: true
    pressure_driven: true
    mean_pressure_gradient: 0.0025
losses:
  data_weight: 10.0
  boundary_weight: 10.0
  momentum_x_weight: 1.0
  momentum_y_weight: 1.0
  momentum_z_weight: 1.0
  continuity_weight: 1.0
  wall_constraint_weight: 5.0
  periodicity_weight: 5.0
  pressure_gradient_weight: 1.0
  prior_weight: 0.3
  source_l1: 1.0e-06
  gradient_penalty: 0.0001
  adaptive_weighting: true
  weight_update_freq: 100
  grad_norm_alpha: 0.15
  causal_weighting: false
training:
  optimizer: adam  # 修改為 adam 以避免 SOAP 在 MPS 上的 float64 問題
  lr: 0.001
  weight_decay: 1.0e-05
  lr_scheduler:
    type: cosine_warm_restarts
    warmup_epochs: 100
    min_lr: 1.0e-06
    T_0: 100
    T_mult: 2
    eta_min: 1.0e-06
    gamma: 0.5
    step_size: 100
  epochs: 10
  max_epochs: 10
  batch_size: 5000
  validation_freq: 5
  checkpoint_freq: 10
  log_interval: 1
  early_stopping:
    enabled: false
    patience: 500
    min_delta: 1.0e-06
  sampling:
    pde_points: 5000
    boundary_points: 1000
    wall_clustering: 0.3
  curriculum: false
  gradient_clip: 1.0
ensemble:
  enable: false
  n_models: 5
  diversity_weight: 0.1
  uncertainty_threshold: 0.15
evaluation:
  grid_resolution:
  - 128
  - 32
  - 128
  metrics:
  - relative_l2
  - wall_shear_stress
  - velocity_profile
  - turbulence_statistics
  - pressure_drop
  - mass_conservation
  - energy_spectrum
  thresholds:
    l2_error: 0.15
    wall_shear_error: 0.08
    velocity_profile_error: 0.1
    rmse_improvement: 0.3
    spectrum_rmse: 0.25
checkpointing:
  save_dir: ./checkpoints
  save_best: true
  save_latest: true
  save_interval: 500
logging:
  log_dir: ./log
  tensorboard: true
  wandb: false
  log_level: INFO
  level: INFO
task_008_gates:
  gate_1_stability:
    no_nan_inf: true
    stage_transition_loss_change: 0.2
  gate_2_convergence:
    relative_l2: 0.15
    wall_shear_stress_error: 0.08
  gate_3_efficiency:
    training_time_hours: 8
    convergence_speedup: 0.2
  gate_4_physics:
    spectrum_rmse: 0.25
    velocity_profile_log_layer_error: 0.15
