# VS-PINN 3D 完整訓練配置
# 目的：使用真實 3D 感測點數據進行完整訓練，追求物理精度與收斂

# 基本實驗設定
experiment:
  name: "vs_pinn_3d_full_training"
  version: "v1.0-full"
  seed: 42
  device: "auto"
  precision: "float32"
  description: "Full 3D VS-PINN training with K=30 sensors for turbulent channel flow reconstruction"

# 資料相關設定 - 簡化配置
data:
  source: "jhtdb"
  dataset: "channel"
  
  jhtdb_config:
    enabled: true
    dataset_name: "channel"
    description: "通道流 (Re_tau=1000) - 測試用"
    domain:
      x: [0, 25.13]
      y: [-1.0, 1.0]
      z: [0, 9.42]
    resolution:
      x: 2048
      y: 512
      z: 1536
    time_range: [0.0, 26.0]
    dt: 0.0065
    variables: ['u', 'v', 'w', 'p']
  
  normalize: true
  cache_dir: "./data/jhtdb/channel_flow_re1000"
  noise_sigma: 0.02
  dropout_prob: 0.10
  
  slice_config:
    plane: "xyz"
    steady_state: true
    time_average_window: [20.0, 26.0]

# 感測點配置 - 使用 K=500 壁面增強選點
sensors:
  K: 500              # 增加到 500 個感測點 (採樣率 ~0.1%)
  selection_method: "qr_pivot"
  sensor_file: "sensors_K500_qr_pivot_3d_wall_enhanced.npz"  # 壁面增強 QR-pivot
  spatial_coverage: "wall_biased"
  wall_enhancement: true
  wall_region_ratio: 0.4
  log_layer_coverage: true

# 模型架構設定 - 保持與正式版一致
model:
  type: "fourier_mlp"
  in_dim: 3
  out_dim: 4
  width: 200
  depth: 8
  activation: "sine"
  
  fourier_m: 64
  fourier_sigma: 5.0
  
  scaling:
    learnable: false
    input_norm: "vs_pinn"
    output_norm:
      u: [0.0, 20.0]      # 流向速度：0 到 ~20 u_tau
      v: [-2.0, 2.0]      # 壁面法向速度：對稱範圍
      w: [-5.0, 5.0]      # 展向速度：對稱範圍
      p: [-300.0, 50.0]   # 壓力：考慮壓力梯度驅動

# 物理設定 - VS-PINN 核心
physics:
  type: "vs_pinn_channel_flow"
  
  nu: 5.0e-5
  rho: 1.0
  
  channel_flow:
    Re_tau: 1000.0
    u_tau: 1.0
    pressure_gradient: 0.0025
    
  domain:
    x_range: [0.0, 25.13]
    y_range: [-1.0, 1.0]
    z_range: [0.0, 9.42]
    
  boundary_conditions:
    wall_velocity: [0.0, 0.0, 0.0]
    wall_location: [-1.0, 1.0]
    periodic_x: true
    periodic_z: true
    pressure_driven: true
  
  # VS-PINN 各向異性縮放因子
  vs_pinn:
    enabled: true
    scaling_factors:
      N_x: 2.0
      N_y: 12.0
      N_z: 2.0
    
    loss_compensation: true
    compensation_factor: 0.00694  # 1 / N_max²

# 損失函數權重
losses:
  data_weight: 10.0
  boundary_weight: 10.0
  
  momentum_x_weight: 1.0
  momentum_y_weight: 1.0
  momentum_z_weight: 1.0
  continuity_weight: 1.0
  
  wall_constraint_weight: 5.0
  periodicity_weight: 2.0
  pressure_gradient_weight: 1.0
  
  prior_weight: 0.3
  source_l1: 1.0e-6
  gradient_penalty: 1.0e-4
  
  adaptive_weighting: true
  weighting_method: "gradnorm"
  weight_update_freq: 100  # 更頻繁更新（測試用）
  grad_norm_alpha: 0.12
  
  causal_weighting: false

# 訓練設定 - 完整訓練
training:
  # Stage 1: Adam 訓練（主要收斂階段）
  stage1:
    optimizer: "adam"
    lr: 1.0e-3
    epochs: 800
    focus: "boundary_and_data"
  
  # Stage 2: L-BFGS 微調（精細調整階段）
  stage2:
    optimizer: "lbfgs"
    lr: 1.0
    max_iter: 200
    history_size: 50
    line_search_fn: "strong_wolfe"
    
  weight_decay: 1.0e-5
  lr_scheduler: "cosine"
  
  max_epochs: 1000
  batch_size: 2048  # 更大 batch size 以覆蓋更多空間
  validation_freq: 50
  checkpoint_freq: 100
  
  early_stopping:
    enabled: false  # 禁用以完成完整訓練（Phase 3 驗證）
    patience: 150
    min_delta: 1.0e-5
    
  sampling:
    pde_points: 4096   # 增加 PDE 殘差點
    boundary_points: 512  # 增加邊界點
    wall_clustering: 0.7  # 更強的壁面聚集
    
  # 啟用課程學習
  curriculum:
    enabled: true
    stages:
      - name: "stage1_boundary_focus"
        epochs: 200
        loss_weights:
          wall_constraint_weight: 15.0
          data_weight: 10.0
      - name: "stage2_pde_balance"
        epochs: 400
        loss_weights:
          momentum_x_weight: 2.0
          momentum_y_weight: 2.0
          momentum_z_weight: 2.0
      - name: "stage3_refinement"
        epochs: 400
        loss_weights:
          prior_weight: 0.5

# Ensemble 與不確定性量化
ensemble:
  enable: false

# 評估設定 - 高解析度評估
evaluation:
  grid_resolution: [128, 256, 128]  # 高解析度評估網格
  
  metrics:
    - "relative_l2"
    - "wall_shear_stress"
    - "velocity_profile"
    - "energy_spectrum"
    - "reynolds_stress"
    - "turbulent_statistics"
    
  thresholds:
    l2_error: 0.15  # 嚴格門檻（目標 ≤15%）
    wall_shear_error: 0.10
    
  vs_pinn_validation:
    check_scaling_consistency: true
    verify_gradient_balance: true
    monitor_condition_number: true

# 日誌與儲存
logging:
  level: "info"
  log_freq: 50  # 每 50 epoch 記錄一次
  save_predictions: true
  save_checkpoints: true
  
  save_velocity_profiles: true
  save_wall_quantities: true
  save_turbulence_fields: true  # 保存湍流場數據
  
  vs_pinn_monitoring:
    log_scaling_factors: true
    log_gradient_norms: true
    log_loss_components: true
  
  wandb:
    project: "vs-pinn-3d-reconstruction"
    entity: null
    tags: ["vs-pinn", "3d", "full-training", "k30", "turbulent-channel"]

# 重現性設定
reproducibility:
  deterministic: true
  benchmark: false
  num_workers: 2

# 效能優化設定
performance:
  mixed_precision: false  # 測試時關閉
  gradient_checkpointing: false
  vectorized_operations: true
  parallel_sampling: false
  max_gpu_memory_fraction: 0.8
  clear_cache_freq: 100

# 測試模式專用
test_mode:
  enabled: false  # 完整訓練模式
  skip_data_download: true  # 使用已快取的資料
  minimal_logging: false
  fast_dev_run: false
