# VS-PINN 修復驗證配置
# 用途：驗證四項核心修復是否解決物理殘差爆炸問題
# 
# 修復清單：
# 1. ✅ 座標標準化一致性（compute_gradients 鏈式法則）
# 2. ✅ 跳過 ManualScalingWrapper（避免雙重標準化破壞 Fourier features）
# 3. ✅ 配置讀取路徑修正（physics.vs_pinn.scaling_factors）
# 4. ✅ 設備分配修正（physics.to(device)）
#
# 預期效果：
# - 初始 PDE 殘差 < 10,000（vs 修復前 2.6M）
# - 訓練穩定收斂，無 NaN/Inf
# - Fourier features 正常工作

# 基本實驗設定
experiment:
  name: "vs_pinn_verify_fixes"
  version: "post-fix-validation"
  seed: 42
  device: "auto"
  precision: "float32"
  description: "Verification test for 4 core VS-PINN fixes"

# 資料相關設定
data:
  source: "jhtdb"
  dataset: "channel"
  
  jhtdb_config:
    enabled: true
    dataset_name: "channel"
    description: "通道流 (Re_tau=1000) - 修復驗證"
    domain:
      x: [0, 25.13]
      y: [-1.0, 1.0]
      z: [0, 9.42]
    resolution:
      x: 2048
      y: 512
      z: 1536
    time_range: [0.0, 26.0]
    dt: 0.0065
    variables: ['u', 'v', 'w', 'p']
  
  normalize: true
  cache_dir: "./data/jhtdb/channel_flow_re1000"
  noise_sigma: 0.02
  dropout_prob: 0.10
  
  slice_config:
    plane: "xyz"
    steady_state: true
    time_average_window: [20.0, 26.0]

# 感測點配置
sensors:
  K: 30
  selection_method: "qr_pivot"
  sensor_file: "sensors_K30_qr_pivot_3d_true.npz"
  spatial_coverage: "wall_biased"
  wall_enhancement: true
  wall_region_ratio: 0.4
  log_layer_coverage: true

# 模型架構設定 - 啟用 Fourier features（測試修復 2）
model:
  type: "fourier_mlp"
  in_dim: 3
  out_dim: 4
  width: 200
  depth: 8
  activation: "sine"
  
  fourier_m: 64
  fourier_sigma: 5.0
  
  # ⚠️ 關鍵：此配置將被 train.py 跳過（is_vs_pinn=True）
  scaling:
    learnable: false
    input_norm: "vs_pinn"  # 此設定會被忽略
    output_norm: "friction_velocity"

# 物理設定 - VS-PINN 核心（測試修復 3 & 4）
physics:
  type: "vs_pinn_channel_flow"  # ✅ 觸發 is_vs_pinn=True
  
  nu: 5.0e-5
  rho: 1.0
  
  channel_flow:
    Re_tau: 1000.0
    u_tau: 1.0
    pressure_gradient: 0.0025
  
  # ✅ 修復 3：正確的配置巢狀路徑
  domain:
    x_range: [0.0, 25.13]   # 物理座標（非標準化）
    y_range: [-1.0, 1.0]
    z_range: [0.0, 9.42]
  
  boundary_conditions:
    wall_velocity: [0.0, 0.0, 0.0]
    wall_location: [-1.0, 1.0]
    periodic_x: true
    periodic_z: true
    pressure_driven: true
  
  # ✅ 修復 3：scaling_factors 在 vs_pinn 子鍵中
  vs_pinn:
    enabled: true
    scaling_factors:
      N_x: 2.0
      N_y: 12.0
      N_z: 2.0
    
    loss_compensation: true
    compensation_factor: 0.00694  # 1 / (12.0)²

# 損失函數權重 - 簡化配置（專注驗證物理殘差）
losses:
  data_weight: 10.0
  boundary_weight: 10.0
  
  momentum_x_weight: 100.0
  momentum_y_weight: 100.0
  momentum_z_weight: 100.0
  continuity_weight: 100.0
  
  wall_constraint_weight: 15.0
  periodicity_weight: 2.0
  pressure_gradient_weight: 1.0
  
  prior_weight: 0.3
  source_l1: 1.0e-6
  gradient_penalty: 1.0e-4
  
  adaptive_weighting: false  # 先關閉，專注基線
  
  # ✅ 測試 warmup（修復 1 影響梯度計算）
  warmup_epochs: 0

# 訓練設定 - 極簡驗證
training:
  stage1:
    optimizer: "adam"
    lr: 1.0e-3
    epochs: 50
    focus: "boundary_and_data"
    
  weight_decay: 1.0e-5
  lr_scheduler: "cosine"
  
  max_epochs: 50
  batch_size: 512
  validation_freq: 5  # 更頻繁驗證
  checkpoint_freq: 50
  
  early_stopping:
    enabled: false
    
  sampling:
    pde_points: 1024
    boundary_points: 128
    wall_clustering: 0.5
    
  curriculum:
    enabled: false

# Ensemble 與不確定性量化
ensemble:
  enable: false

# 評估設定
evaluation:
  grid_resolution: [64, 128, 64]
  
  metrics:
    - "relative_l2"
    - "wall_shear_stress"
    - "velocity_profile"
    
  thresholds:
    l2_error: 0.30
    wall_shear_error: 0.20
    
  vs_pinn_validation:
    check_scaling_consistency: true
    verify_gradient_balance: true
    monitor_condition_number: false

# 日誌與儲存 - 詳細監控修復效果
logging:
  level: "info"
  log_freq: 10  # 每 10 步記錄一次
  save_predictions: true
  save_checkpoints: true
  
  save_velocity_profiles: true
  save_wall_quantities: true
  save_turbulence_fields: false
  
  vs_pinn_monitoring:
    log_scaling_factors: true
    log_gradient_norms: true
    log_loss_components: true  # 關鍵：監控 PDE 殘差
  
  wandb:
    project: "vs-pinn-fixes-verification"
    entity: null
    tags: ["vs-pinn", "verification", "post-fix", "fourier-enabled"]

# 重現性設定
reproducibility:
  deterministic: true
  benchmark: false
  num_workers: 2

# 效能優化設定
performance:
  mixed_precision: false
  gradient_checkpointing: false
  vectorized_operations: true
  parallel_sampling: false
  max_gpu_memory_fraction: 0.8
  clear_cache_freq: 100

# 測試模式專用
test_mode:
  enabled: true
  skip_data_download: true
  minimal_logging: false
  fast_dev_run: false
