# VS-PINN 快速測試配置 - 2D 版本 (維度修復)
# 目的：驗證訓練流程能正常運行，不追求收斂
# 使用現有 2D 感測點數據進行快速驗證

# 基本實驗設定
experiment:
  name: "vs_pinn_test_quick_2d"
  version: "v1.0-test-2d"
  seed: 42
  device: "auto"
  precision: "float32"
  description: "Quick 2D test for VS-PINN training pipeline (dimension fix)"

# 資料相關設定 - 2D 切片配置
data:
  source: "jhtdb"
  dataset: "channel"
  
  jhtdb_config:
    enabled: true
    dataset_name: "channel"
    description: "通道流 (Re_tau=1000) - 2D 切片測試"
    domain:
      x: [0, 25.13]
      y: [-1.0, 1.0]
      # z 維度省略（2D 切片）
    resolution:
      x: 2048
      y: 512
    time_range: [0.0, 26.0]
    dt: 0.0065
    variables: ['u', 'v', 'p']  # 2D：無 w 分量
  
  normalize: true
  cache_dir: "./data/jhtdb/channel_flow_re1000"
  noise_sigma: 0.02
  dropout_prob: 0.10
  
  slice_config:
    plane: "xy"  # 明確指定 2D 切片
    steady_state: true
    time_average_window: [20.0, 26.0]

# 感測點配置 - 使用現有 2D 數據
sensors:
  K: 30
  selection_method: "qr_pivot"
  sensor_file: "sensors_K30_qr_pivot_3d.npz"  # 實際是 2D 數據
  spatial_coverage: "wall_biased"
  wall_enhancement: true
  wall_region_ratio: 0.4
  log_layer_coverage: true

# 模型架構設定 - 2D 修正
model:
  type: "fourier_mlp"
  in_dim: 2   # 修正：2D 輸入 (x, y)
  out_dim: 3  # 修正：2D 輸出 (u, v, p)
  width: 200
  depth: 8
  activation: "sine"
  
  fourier_m: 64
  fourier_sigma: 5.0
  
  scaling:
    learnable: false
    input_norm: "vs_pinn"
    output_norm: "friction_velocity"

# 物理設定 - 2D Navier-Stokes
physics:
  type: "ns_2d"  # 修正：使用 2D 物理模組
  
  nu: 5.0e-5
  rho: 1.0
  
  channel_flow:
    Re_tau: 1000.0
    u_tau: 1.0
    pressure_gradient: 0.0025
    
  domain:
    x_range: [0.0, 25.13]
    y_range: [-1.0, 1.0]
    # 移除 z_range
    
  boundary_conditions:
    wall_velocity: [0.0, 0.0]  # 2D：只有 u, v
    wall_location: [-1.0, 1.0]
    periodic_x: true
    pressure_driven: true
  
  # VS-PINN 縮放因子（2D 版本）
  vs_pinn:
    enabled: true
    scaling_factors:
      N_x: 2.0
      N_y: 12.0
      # 移除 N_z
    
    loss_compensation: true
    compensation_factor: 0.00694  # 1 / N_max²

# 損失函數權重 - 2D 調整
losses:
  data_weight: 10.0
  boundary_weight: 10.0
  
  momentum_x_weight: 1.0
  momentum_y_weight: 1.0
  # 移除 momentum_z_weight
  continuity_weight: 1.0
  
  wall_constraint_weight: 5.0
  periodicity_weight: 2.0
  pressure_gradient_weight: 1.0
  
  prior_weight: 0.3
  source_l1: 1.0e-6
  gradient_penalty: 1.0e-4
  
  adaptive_weighting: true
  weighting_method: "gradnorm"
  weight_update_freq: 100
  grad_norm_alpha: 0.12
  
  causal_weighting: false

# 訓練設定 - 極簡測試
training:
  stage1:
    optimizer: "adam"
    lr: 1.0e-3
    epochs: 50
    focus: "boundary_and_data"
    
  weight_decay: 1.0e-5
  lr_scheduler: "cosine"
  
  max_epochs: 50
  batch_size: 512
  validation_freq: 10
  checkpoint_freq: 50
  
  early_stopping:
    enabled: false
    
  sampling:
    pde_points: 1024
    boundary_points: 128
    wall_clustering: 0.5
    
  curriculum:
    enabled: false

# Ensemble 與不確定性量化
ensemble:
  enable: false

# 評估設定 - 2D 簡化
evaluation:
  grid_resolution: [64, 128]  # 2D 網格
  
  metrics:
    - "relative_l2"
    - "wall_shear_stress"
    - "velocity_profile"
    
  thresholds:
    l2_error: 0.30
    wall_shear_error: 0.20
    
  vs_pinn_validation:
    check_scaling_consistency: true
    verify_gradient_balance: true
    monitor_condition_number: false

# 日誌與儲存
logging:
  level: "info"
  log_freq: 20
  save_predictions: true
  save_checkpoints: true
  
  save_velocity_profiles: true
  save_wall_quantities: true
  save_turbulence_fields: false
  
  vs_pinn_monitoring:
    log_scaling_factors: true
    log_gradient_norms: true
    log_loss_components: true
  
  wandb:
    project: "vs-pinn-test-2d"
    entity: null
    tags: ["vs-pinn", "test", "2d", "dimension-fix"]

# 重現性設定
reproducibility:
  deterministic: true
  benchmark: false
  num_workers: 2

# 效能優化設定
performance:
  mixed_precision: false
  gradient_checkpointing: false
  vectorized_operations: true
  parallel_sampling: false
  max_gpu_memory_fraction: 0.8
  clear_cache_freq: 100

# 測試模式專用
test_mode:
  enabled: true
  skip_data_download: true
  minimal_logging: false
  fast_dev_run: false
